### ISSUE TITLE
Monitoring > upgrade the current monitor to a batching monitor

### ISSUE THREAD

**Issue by junhuif** [theplant/appkit#13]
From: https://github.com/theplant/appkit/pull/12#pullrequestreview-121660244

> At the moment, each data point is sent in a single request, right? So with lots of requests, the monitor will make lots of requests to InfluxDB.

> This can be changed so that points are "batched" into a queue, and then a worker sends the queue to InfluxDB after P points, or after S seconds.

**Comment by lifenod** [comment]
haha the InfluxDB is very busy https://github.com/theplant/performance/blob/ad1ee830151d9db8955690a316f9d0a236747dad/aigle/units/page-all-pricedown/prod-2018-12-24-reports/README.md
