### ISSUE TITLE
Upgrade Airbrake package

### ISSUE THREAD

**Issue by lifenod** [theplant/appkit#35]
I found the latest version of `gobrake` already supports async notify: https://github.com/airbrake/gobrake/blob/9aadbc7c73469aca00e218e755c57662ff1d4fbf/notifier.go#L220.
So we can fix this simply: https://github.com/theplant/lacoste3/issues/1959

But gopkg.in is not supported any more: https://github.com/airbrake/gobrake/issues/53#issuecomment-372944694, I try to use v3 but deos not work, got error

```
../../../../gopkg.in/airbrake/gobrake.v3/code_hunk.go:9:2: cannot find package "github.com/airbrake/gobrake/internal/lrucache" in any of:
	/usr/local/opt/go/libexec/src/github.com/airbrake/gobrake/internal/lrucache (from $GOROOT)
	/Users/lifenod/Code/Go/src/github.com/airbrake/gobrake/internal/lrucache (from $GOPATH)
```

so we need to use `vgo` or not?
@bodhi any idea?

**Comment by idealhack** [comment]
it's `go mod` now :trollface:

**Comment by bodhi** [comment]
But Appkit doesn't have any dependency management now :trollface:

**Comment by lifenod** [comment]
I mean `vgo` is Go modules, also is `go mod`.

So let's use the master :trollface:
