### ISSUE TITLE
Easier way to log an error with stack

### ISSUE THREAD

**Issue by sunfmin** [theplant/appkit#4]
From @lifenod 

If I want log stack, I must write

```go
logger.WithError(
	kerrs.Wrapv(
		err,
		"msg",
		"key", "value",
	),
).Log()

```
Looks like ugly.

@sunfmin Add WithAndLogError function ?

**Comment by sunfmin** [comment]
@bodhi Do you think we should add a convenient func?

**Comment by bodhi** [comment]
Sure.

**Comment by bodhi** [comment]
@sunfmin can this be closed?
