### ISSUE TITLE
Should we change log level to adopt Stackdriver levels?

### ISSUE THREAD

**Issue by sunfmin** [theplant/appkit#48]
https://cloud.google.com/logging/docs/reference/v2/rest/v2/LogEntry#LogSeverity

DEFAULT | (0) The log entry has no assigned severity level.
-- | --
DEBUG | (100) Debug or trace information.
INFO | (200) Routine information, such as ongoing status or performance.
NOTICE | (300) Normal but significant events, such as start up, shut down, or a configuration change.
WARNING | (400) Warning events might cause problems.
ERROR | (500) Error events are likely to cause problems.
CRITICAL | (600) Critical events cause more severe problems or outages.
ALERT | (700) A person must take an action immediately.
EMERGENCY | (800) One or more systems are unusable.

**Comment by bodhi** [comment]
I think it's already a bit hard to decide the level for some things, I don't know if adding more levels will be helpful?

For reference, these are the levels we don't have:


DEFAULT | (0) The log entry has no assigned severity level.
-- | --
NOTICE | (300) Normal but significant events, such as start up, shut down, or a configuration change.
ALERT | (700) A person must take an action immediately.
EMERGENCY | (800) One or more systems are unusable.

Have you or the team seen some problems by not having these levels? Or do you think it would be useful to be consistent with the StackDriver levels?

**Comment by sunfmin** [comment]
I think just two levels is enough, `Info` and `Alert`, one is normal logging, the other needs person to take an action...

**Comment by bodhi** [comment]
I mostly agree, but there's a difference between "you need to do something about this *right now* and you should do something about this when you start work in the morning"

**Comment by bodhi** [comment]
Since neither of us think the extra levels would be useful, can we close this?
