### ISSUE TITLE
Redirect standard log.Println logs to appkit log?

### ISSUE THREAD

**Issue by sunfmin** [theplant/appkit#5]
```go
import (
	"os"
	stdlog "log"
	kitlog "github.com/go-kit/kit/log"
)

func main() {
	logger := kitlog.NewJSONLogger(kitlog.NewSyncWriter(os.Stdout))
	stdlog.SetOutput(kitlog.NewStdlibAdapter(logger))
	stdlog.Print("I sure like pie")
}
// Output:
// {"msg":"I sure like pie","ts":"2016/01/01 12:34:56"}

```

@bodhi Do you think we should add the redirect by default when you `log.Default()`?

**Comment by bodhi** [comment]
> add the redirect by default

I think it should require explicit action.

**Comment by sunfmin** [comment]
Add a func like `log.RedirectGoStandardLogTo(l)` to set it up? Not sure about the func name...

**Comment by bodhi** [comment]
basically this?

```
import (
	"log"
)


func SetStdLogOutput(logger Logger) {
    log.SetOutput(NewStdlibAdapter(logger))
}
````

Or if `Logger` implements [`io.Writer`](https://godoc.org/io#Writer), you could just pass it straight in:

```
stdlog.SetOutput(logger)
```

For reference `io.Writer` looks like this:

```
type Writer interface {
    Write(p []byte) (n int, err error)
}
```

**Comment by sunfmin** [comment]
Cool
